theme: jekyll-theme-hacker
title: "Lars Ekman's blog"
description: "Things I like to document for myself and others"
url: "https://uablrek.github.io"

author:
  name: "Lars Ekman"
  location: "Stockholm, Sweden"
  email: "uablrek@gmail.com"
  github: "uablrek"
