remote_theme: "jekyll/minima@1e8a445"
title: "Lars Ekman's blog"
description: "Saker jag vill skriva om för mig själv och andra"
url: "https://uablrek.github.io"

author:
  name: "Lars Ekman"
  location: "Stockholm, Sweden"
  email: "uablrek@gmail.com"
  github: "uablrek"

defaults:
  - scope:
      path: ""
    values:
      language: "sv"
  - scope:
      path: "en"
    values:
      language: "en"
